---
title: "fish_survey"
author: "Charles Hendrickson"
date: "2/24/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# load packages
librarian::shelf(ggplot2,lubridate, tidyverse, janitor, plotly)
```


The data is from the Environmental Data Initiative data portal. https://portal.edirepository.org/nis/mapbrowse?packageid=knb-lter-mcr.6.61

The Anual Fish Survey data contains fish transect visual counts repeated annually include species, fish length, estimated biomass, and trophic group.
```{r}
# load data
annual_fish_survey_data <- read.csv("data/MCR_LTER_Annual_Fish_Survey_20220119.csv")

```


```{r}
# explore data
str(annual_fish_survey_data)
```

Clean data column names and 
```{r}
# make all column names lowercase 
annual_fish_survey_data <- annual_fish_survey_data %>%
  clean_names()

# Change data type of the column 'site' from numeric to a factor
annual_fish_survey_data$site <- as.factor(annual_fish_survey_data$site)
```

Filter data 
```{r}
# Group by year, site, and biomass
annual_biomass_data <- annual_fish_survey_data %>%
  filter(coarse_trophic == "Primary Consumer") %>% 
  group_by(year, site) %>%
  summarise(mean_biomass = mean(biomass))
```


Line chart 
```{r}
# Plot biomass by year and color the sites
biomass_plot <- ggplot(data = annual_biomass_data, aes(x = year, y = mean_biomass, color = site)) +
  geom_point() + 
  geom_line(aes(group = site)) +
  labs(title = "Fish Biomass in Moorea, French Polynesia (2006-2021)",
       x = "Year",
       y = "Average Biomass")


# Make plot interactive 
ggplotly(biomass_plot)
```


Stacked bar chart 
```{r}
# Plot biomass by year and color the sites
biomass_plot <- ggplot(data = annual_biomass_data, aes(x = year, y = mean_biomass, fill = site)) +
  geom_bar(position="stack", stat="identity") +
  labs(title = "Fish Biomass in Moorea, French Polynesia (2006-2021)",
       x = "Year",
       y = "Average Biomass")


# Make plot interactive 
ggplotly(biomass_plot)
```

Change in mean_biomass over time 
```{r}
# Find the average biomass for a site per year 


# Find the average biomass of the site across all years 


# Subtract the two to normalize the observations 


```





































